### ISSUE TITLE
Help needed for question 2 of the assignment 7

### ISSUE THREAD

**Issue by KVUGA** [leombastos/2024_ppa#42]
When it is mentioned "the same we used in class", does it mean that the statistics parameters we studied in the yield monitoring classes such as mean, median etc?

**Comment by leombastos** [comment]
Hi Kumar.
Thanks for bringing this up.
This answer is based on going through the exercise, which we originally planned to do on Friday.
Since classes were cancelled, we have not gone through this yet, and so you don't have the needed information to answer it.

I'll send an email to the whole class mentioning this, and extending the deadline for submission to Monday 11:59 pm to give you all time to answer it after we go through the exercise in class.

**Comment by KVUGA** [comment]
Thanks a lot for the clarification. Looking forward to tomorrow's class.
